name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and test all labs
        run: |
          for dir in lab*; do
            if [ -d "$dir" ] && [ -f "$dir/CMakeLists.txt" ]; then
              echo "=== Building and testing $dir ==="
              cmake -S "$dir" -B "$dir/build"
              cmake --build "$dir/build"
              ctest --test-dir "$dir/build"
            fi
          done
