name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Build and Test all labs
      run: |
        for dir in lab*; do
          if [ -f "$dir/CMakeLists.txt" ]; then
            echo "Building project in $dir"
            cmake -S "$dir" -B "$dir/build"
            cmake --build "$dir/build"
            echo "Running tests in $dir"
            ctest --test-dir "$dir/build" --output-on-failure
          fi
        done
